import { Injectable } from '@angular/core';

// ELE E COMPATIVEL COM O SISTEMA DE INJEÇÃO DE DEPENDENCIA ESSA CLASS E AQUI
@Injectable({
  providedIn: 'root'
})
export class CoursesService {

  constructor() {
    // SEMPRE VAMOS TER SEMPRE UMA INSTANCIA DE UM SERVIÇO
    // POR EXEMPLO
    // A CADA INSTANCIAMENTO DE UM COMPONENTE DO CURSO
    // ESTAMOS PROVENDO ESSE SERVIÇO PRA ELE
    // SO QUE UTILIZAMOS SEMPRE A MESMA INSTANCIA PRA TODOS
    console.log('CRIAÇÃO DO COURSES SERVICES INSTANCIA');
  }
}
